application: fofou
version: 1
runtime: python
api_version: 1

handlers:
- url: /fofou.css
  static_files: fofou.css
  upload: fofou.css

- url: /fofou.js
  static_files: fofou.js
  upload: fofou.jss

- url: /graphics
  static_dir: graphics

- url: .*
  script: main.py

